name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Tests
        run: npm test

      - name: Set status check for 'Checking Tests'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success', // or 'failure' based on test results
              description: 'Tests have completed',
              context: 'Checking Tests'
            })# name: Checking Tests

# on:
#   pull_request:
#     branches:
#       - develop

# jobs:
#   test:
#     name: Checking Tests
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 21.x

#       - name: Install dependencies
#         run: npm install
      
#       - name: Build App
#         run: npm run build

#       - name: Run vitest tests
#         run: npm run test

#       - name: Run componest test
#         run: test-component

